version: '3'
services:
  api:
    image: strapi/strapi
    volumes:
      - ./app:/srv/app
    ports:
      - 1337:1337

  # ui:
  #   build:
  #     context: ./ui
  #     dockerfile: Dockerfile
  #   restart: 'no'
  #   env_file: ./ui/.env
  #   volumes:
  #     - static_node_modules:/web/app/node_modules
  #     - ./ui:/web/app

  nginx:
    image: nginx:latest
    # depends_on:
    #   - ui
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ui/bundle:/web/app/bundle
    ports:
      - 80:80

volumes:
  static_node_modules:
